# Generated by Django 5.1.7 on 2025-03-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="twofactorauth",
            name="is_2fa_enabled",
        ),
        migrations.AddField(
            model_name="twofactorauth",
            name="email_method",
            field=models.CharField(
                blank=True,
                choices=[("gmail", "Gmail"), ("outlook", "Outlook")],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="twofactorauth",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
