# Generated by Django 5.1.7 on 2025-03-22 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_twofactorauth_is_2fa_enabled_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="twofactorauth",
            name="phone_number",
        ),
    ]
