# Generated by Django 5.1.6 on 2025-04-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("count", models.IntegerField(default=0)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("min_quantity", models.IntegerField(blank=True, null=True)),
                ("max_quantity", models.IntegerField(blank=True, null=True)),
                ("template_message", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="InventoryRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product", models.CharField(max_length=100)),
                ("quantity", models.IntegerField()),
                ("recorded_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="ThresholdSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product", models.CharField(max_length=100)),
                ("min_quantity", models.PositiveIntegerField()),
                ("max_quantity", models.PositiveIntegerField()),
                ("color", models.CharField(default="#000000", max_length=20)),
                (
                    "template_message",
                    models.CharField(default="Only {stock} units left", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
