# Generated by Django 5.1.6 on 2025-04-10 21:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("product", models.CharField(max_length=100)),
                ("quantity", models.PositiveIntegerField()),
                ("purchase_rate", models.FloatField()),
                ("sales_rate", models.FloatField()),
                ("sold_quantity", models.PositiveIntegerField()),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
